name: Scan Container

on:
  push:
    branches:
    - "master"  # run for master branch

jobs:
  build-test-images:
    runs-on: ubuntu-latest
    env:
      GROUP: demo 
    strategy:
      matrix:
        repo: ["openapi", "healthcheck"]
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ${{ matrix.repo }}
        push: false
        load: true
        tags: ${{ env.GROUP }}/${{ matrix.repo }}:${{ github.sha }}

    - name: Scan image
      uses: anchore/scan-action@v3
      with:
        image: ${{ env.GROUP }}/${{ matrix.repo }}:${{ github.sha }}